# Generated by Django 4.2 on 2023-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loanagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_pl', models.CharField(max_length=100)),
                ('interest_bl', models.CharField(max_length=100)),
                ('interest_hl', models.CharField(max_length=100)),
                ('interest_el', models.CharField(max_length=100)),
                ('interest_vl', models.CharField(max_length=100)),
                ('principal_pl', models.CharField(max_length=100)),
                ('principal_bl', models.CharField(max_length=100)),
                ('principal_hl', models.CharField(max_length=100)),
                ('principal_el', models.CharField(max_length=100)),
                ('principal_vl', models.CharField(max_length=100)),
                ('time_pl', models.CharField(max_length=100)),
                ('time_bl', models.CharField(max_length=100)),
                ('time_hl', models.CharField(max_length=100)),
                ('time_el', models.CharField(max_length=100)),
                ('time_vl', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bankdetails',
            },
        ),
    ]
